server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mostarc.eyeglass.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.190.17.179:3306/eyeglass?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 246810

#logging:
#  level:
#    com.mostarc.eyeglass.mapper: debug
